#!/usr/bin/env python3
"""
launcher.py – Configuration GUI for FRC Pit Safety Monitor

Tkinter kiosk that auto-detects cameras, lets you tweak settings,
then hands off to pi_deploy.py after a countdown.
"""

import tkinter as tk
from tkinter import ttk
import subprocess
import os
import sys
import threading

CONFIG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.env")
MAIN_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pi_deploy.py")
AUTO_START_DELAY = 15   # seconds before auto-launching
CAMERA_POLL_MS = 2000   # how often to check for a camera


def detect_working_camera():
    """Return (index, label) for first working camera, or (None, None)."""
    # Try Pi Camera via libcamera
    try:
        result = subprocess.run(
            ["libcamera-hello", "--list-cameras"],
            capture_output=True, text=True, timeout=3
        )
        if "Available cameras" in result.stdout and "No cameras" not in result.stdout:
            return -1, "Pi Camera (libcamera)"
    except Exception:
        pass

    # Try USB cameras 0-4
    try:
        import cv2
    except Exception:
        return None, None
    for i in range(5):
        try:
            cap = cv2.VideoCapture(i)
            if cap.isOpened():
                ret, frame = cap.read()
                cap.release()
                if ret and frame is not None:
                    return i, f"USB Camera {i}"
        except Exception:
            pass

    return None, None


def load_config():
    """Load config from config.env, falling back to defaults."""
    config = {
        "CONFIRM_FRAMES": "8",
        "MIN_CONF": "0.70",
        "PROCESS_EVERY_N": "2",
        "TFLITE_THREADS": "2",
        "CAM_RETRY_DELAY": "5",
        "DATA_SAVE_INT": "3",
        "MODEL_PATH": "",
        "CAMERA_INDEX": "auto",
        "FULLSCREEN": "1",
        "DEMO_MODE": "1",
    }

    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        config[key.strip()] = value.strip()
        except Exception as e:
            print(f"[LAUNCHER] Failed to read config.env: {e}", file=sys.stderr)

    return config


def save_config(config):
    """Write config back to config.env."""
    with open(CONFIG_FILE, "w") as f:
        f.write("# FRC Pit Safety Monitor Configuration\n")
        f.write("# Generated by launcher.py\n\n")
        f.write("# Detection Settings\n")
        f.write(f"CONFIRM_FRAMES={config['CONFIRM_FRAMES']}\n")
        f.write(f"MIN_CONF={config['MIN_CONF']}\n\n")
        f.write("# Performance Settings\n")
        f.write(f"PROCESS_EVERY_N={config['PROCESS_EVERY_N']}\n")
        f.write(f"TFLITE_THREADS={config['TFLITE_THREADS']}\n\n")
        f.write("# Camera Settings\n")
        f.write(f"CAMERA_INDEX={config['CAMERA_INDEX']}\n")
        f.write(f"CAM_RETRY_DELAY={config['CAM_RETRY_DELAY']}\n\n")
        f.write("# Training Data Collection (seconds between captures, 0 to disable)\n")
        f.write(f"DATA_SAVE_INT={config['DATA_SAVE_INT']}\n\n")
        f.write("# Display / kiosk (1 = fullscreen, touchless demo)\n")
        f.write(f"FULLSCREEN={config.get('FULLSCREEN', '1')}\n")
        f.write(f"DEMO_MODE={config.get('DEMO_MODE', '1')}\n\n")
        f.write("# Model path (empty for auto-detect)\n")
        f.write(f"MODEL_PATH={config.get('MODEL_PATH', '')}\n")


class LauncherApp:
    def __init__(self, root):
        self.root = root
        self.root.title("FRC Pit Safety Monitor")

        self.config = load_config()
        self.fullscreen = self.config.get("FULLSCREEN", "1") == "1"
        self.demo_mode = self.config.get("DEMO_MODE", "1") == "1"

        if self.fullscreen:
            self.root.attributes("-fullscreen", True)
            self.root.resizable(True, True)
        else:
            self.root.geometry("480x520")
            self.root.resizable(False, False)
            self.root.update_idletasks()
            x = (self.root.winfo_screenwidth() - 480) // 2
            y = (self.root.winfo_screenheight() - 520) // 2
            self.root.geometry(f"480x520+{x}+{y}")

        self.countdown = AUTO_START_DELAY
        self.countdown_active = False
        self.detected_camera = None
        self._handoff_armed = False
        self._poll_scheduled = False
        self._autosave_after_id = None

        self.create_widgets()

        # In demo mode, hide manual controls — it's fully touchless
        if self.demo_mode:
            self.start_btn.grid_remove()
            self.pause_btn.grid_remove()
            self.quit_btn.grid_remove()

        self.schedule_camera_poll()
        self._setup_autosave_hooks()

    @staticmethod
    def _safe_int(raw, default, minimum=None):
        try:
            value = int(raw)
        except (TypeError, ValueError):
            value = default
        if minimum is not None:
            value = max(minimum, value)
        return value

    @staticmethod
    def _safe_float(raw, default, minimum=None, maximum=None):
        try:
            value = float(raw)
        except (TypeError, ValueError):
            value = default
        if minimum is not None:
            value = max(minimum, value)
        if maximum is not None:
            value = min(maximum, value)
        return value

    # ── Autosave on change (debounced) ───────────────────
    def _setup_autosave_hooks(self):
        def changed(*_args):
            self._schedule_autosave()

        for var in (self.frame_skip_var, self.conf_var, self.confirm_var, self.data_enabled_var):
            try:
                var.trace_add("write", changed)
            except Exception:
                pass

        def entry_changed(_event=None):
            self._schedule_autosave()

        try:
            self.data_interval_entry.bind("<KeyRelease>", entry_changed)
            self.data_interval_entry.bind("<FocusOut>", entry_changed)
        except Exception:
            pass

    def _schedule_autosave(self):
        try:
            if self._autosave_after_id is not None:
                self.root.after_cancel(self._autosave_after_id)
        except Exception:
            pass
        self._autosave_after_id = self.root.after(250, self._autosave_now)

    def _autosave_now(self):
        self._autosave_after_id = None
        try:
            self.save_and_get_config()
        except Exception:
            # Avoid crashing the kiosk for a save failure.
            pass

    # ── Camera polling ───────────────────────────────────
    def schedule_camera_poll(self):
        if not self._poll_scheduled:
            self._poll_scheduled = True
            self.root.after(100, self.poll_camera_once)

    def poll_camera_once(self):
        """Start a background thread to detect the camera without blocking the UI."""
        self._poll_scheduled = False

        def _detect():
            idx, name = detect_working_camera()
            # Always deliver the result back to the Tkinter main thread.
            try:
                self.root.after(0, lambda i=idx, n=name: self._on_camera_result(i, n))
            except Exception:
                pass  # window may have been destroyed

        threading.Thread(target=_detect, daemon=True).start()

    def _on_camera_result(self, idx, name):
        """Called on the Tkinter main thread with the result of camera detection."""
        if idx is None:
            self.detected_camera = None
            self.camera_status.config(text="Waiting for camera… (USB / ribbon)", foreground="red")
            self.countdown_label.config(text="No camera — retrying automatically", fg="#cc6600")
            self.countdown_active = False
            self._handoff_armed = False
            self.root.after(CAMERA_POLL_MS, self.poll_camera_once)
            return

        self.detected_camera = (idx, name)
        self.camera_status.config(text=f"Found: {name}", foreground="green")
        self.config["CAMERA_INDEX"] = str(idx)

        # Start the countdown the first time we see a camera
        if not self._handoff_armed:
            self._handoff_armed = True
            self.countdown = AUTO_START_DELAY
            self.countdown_active = True
            self.update_countdown()

    # ── UI setup ─────────────────────────────────────────
    def create_widgets(self):
        tk.Label(self.root, text="FRC Pit Safety Monitor",
                 font=("Helvetica", 18, "bold")).pack(pady=(15, 5))
        tk.Label(self.root, text="Configure settings before starting",
                 font=("Helvetica", 10), fg="gray").pack(pady=(0, 15))

        main_frame = ttk.Frame(self.root, padding=20)
        main_frame.pack(fill="both", expand=True)

        # Camera status
        ttk.Label(main_frame, text="Camera:", font=("Helvetica", 11, "bold")).grid(
            row=0, column=0, sticky="w", pady=(0, 5))
        self.camera_status = ttk.Label(main_frame, text="Detecting…", foreground="gray")
        self.camera_status.grid(row=0, column=1, sticky="w", padx=(10, 0), pady=(0, 5))

        # Frame skip slider
        ttk.Label(main_frame, text="Process Every N Frames:", font=("Helvetica", 11, "bold")).grid(
            row=1, column=0, sticky="w", pady=(15, 5))
        frame_skip_frame = ttk.Frame(main_frame)
        frame_skip_frame.grid(row=1, column=1, sticky="w", padx=(10, 0), pady=(15, 5))
        self.frame_skip_var = tk.IntVar(
            value=self._safe_int(self.config.get("PROCESS_EVERY_N", 2), 2, minimum=1)
        )
        self.frame_skip_scale = ttk.Scale(
            frame_skip_frame, from_=1, to=5, variable=self.frame_skip_var,
            orient="horizontal", length=150,
            command=lambda v: self.frame_skip_label.config(text=str(int(float(v)))))
        self.frame_skip_scale.pack(side="left")
        self.frame_skip_label = ttk.Label(frame_skip_frame, text=str(self.frame_skip_var.get()), width=3)
        self.frame_skip_label.pack(side="left", padx=(10, 0))
        ttk.Label(main_frame, text="(Higher = faster, less accurate)",
                  font=("Helvetica", 9), foreground="gray").grid(row=2, column=1, sticky="w", padx=(10, 0))

        # Confidence slider
        ttk.Label(main_frame, text="Detection Confidence:", font=("Helvetica", 11, "bold")).grid(
            row=3, column=0, sticky="w", pady=(15, 5))
        conf_frame = ttk.Frame(main_frame)
        conf_frame.grid(row=3, column=1, sticky="w", padx=(10, 0), pady=(15, 5))
        self.conf_var = tk.DoubleVar(
            value=self._safe_float(self.config.get("MIN_CONF", 0.70), 0.70, minimum=0.3, maximum=0.9)
        )
        self.conf_scale = ttk.Scale(
            conf_frame, from_=0.3, to=0.9, variable=self.conf_var,
            orient="horizontal", length=150,
            command=lambda v: self.conf_label.config(text=f"{float(v):.2f}"))
        self.conf_scale.pack(side="left")
        self.conf_label = ttk.Label(conf_frame, text=f"{self.conf_var.get():.2f}", width=5)
        self.conf_label.pack(side="left", padx=(10, 0))
        ttk.Label(main_frame, text="(Higher = fewer false positives)",
                  font=("Helvetica", 9), foreground="gray").grid(row=4, column=1, sticky="w", padx=(10, 0))

        # Confirm frames slider
        ttk.Label(main_frame, text="Confirm Frames:", font=("Helvetica", 11, "bold")).grid(
            row=5, column=0, sticky="w", pady=(15, 5))
        confirm_frame = ttk.Frame(main_frame)
        confirm_frame.grid(row=5, column=1, sticky="w", padx=(10, 0), pady=(15, 5))
        self.confirm_var = tk.IntVar(
            value=self._safe_int(self.config.get("CONFIRM_FRAMES", 8), 8, minimum=3)
        )
        self.confirm_scale = ttk.Scale(
            confirm_frame, from_=3, to=20, variable=self.confirm_var,
            orient="horizontal", length=150,
            command=lambda v: self.confirm_label.config(text=str(int(float(v)))))
        self.confirm_scale.pack(side="left")
        self.confirm_label = ttk.Label(confirm_frame, text=str(self.confirm_var.get()), width=3)
        self.confirm_label.pack(side="left", padx=(10, 0))
        ttk.Label(main_frame, text="(Frames before violation triggers)",
                  font=("Helvetica", 9), foreground="gray").grid(row=6, column=1, sticky="w", padx=(10, 0))

        ttk.Separator(main_frame, orient="horizontal").grid(
            row=7, column=0, columnspan=2, sticky="ew", pady=15)

        # Training data collection toggle
        ttk.Label(main_frame, text="Training Data:", font=("Helvetica", 11, "bold")).grid(
            row=8, column=0, sticky="w", pady=(5, 5))
        data_frame = ttk.Frame(main_frame)
        data_frame.grid(row=8, column=1, sticky="w", padx=(10, 0), pady=(5, 5))
        current_interval = self._safe_float(self.config.get("DATA_SAVE_INT", 0), 0, minimum=0)
        self.data_enabled_var = tk.BooleanVar(value=current_interval > 0)
        self.data_check = ttk.Checkbutton(
            data_frame, text="Save raw images every",
            variable=self.data_enabled_var, command=self.toggle_data_interval)
        self.data_check.pack(side="left")
        self.data_interval_var = tk.StringVar(
            value=str(int(current_interval)) if current_interval > 0 else "3")
        self.data_interval_entry = ttk.Entry(data_frame, textvariable=self.data_interval_var, width=4)
        self.data_interval_entry.pack(side="left", padx=(5, 0))
        ttk.Label(data_frame, text="sec").pack(side="left", padx=(3, 0))
        ttk.Label(main_frame, text="(Saves to data_collection/ folder)",
                  font=("Helvetica", 9), foreground="gray").grid(row=9, column=1, sticky="w", padx=(10, 0))
        self.toggle_data_interval()

        ttk.Separator(main_frame, orient="horizontal").grid(
            row=10, column=0, columnspan=2, sticky="ew", pady=15)

        # Countdown label
        self.countdown_label = tk.Label(
            main_frame, text="Waiting for camera…", font=("Helvetica", 12), fg="#0066cc")
        self.countdown_label.grid(row=11, column=0, columnspan=2, pady=(5, 15))

        # Action buttons
        button_frame = ttk.Frame(main_frame)
        button_frame.grid(row=12, column=0, columnspan=2)
        self.start_btn = ttk.Button(button_frame, text="Start Now", command=self.start_monitor, width=15)
        self.start_btn.grid(row=0, column=0, padx=5)
        self.pause_btn = ttk.Button(button_frame, text="Pause Countdown", command=self.toggle_countdown, width=15)
        self.pause_btn.grid(row=0, column=1, padx=5)
        self.quit_btn = ttk.Button(button_frame, text="Quit", command=self.quit_app, width=10)
        self.quit_btn.grid(row=0, column=2, padx=5)

        # Pause countdown if the user interacts with a setting
        for widget in [self.frame_skip_scale, self.conf_scale, self.confirm_scale,
                       self.data_check, self.data_interval_entry]:
            widget.bind("<Button-1>", self.on_interaction)
            widget.bind("<Key>", self.on_interaction)

    # ── Widget callbacks ─────────────────────────────────
    def toggle_data_interval(self):
        state = "normal" if self.data_enabled_var.get() else "disabled"
        self.data_interval_entry.config(state=state)

    def on_interaction(self, event=None):
        """Pause the countdown if the user starts tweaking settings."""
        if self.demo_mode:
            return
        if self.countdown_active and self.countdown > 5:
            self.countdown_active = False
            self.pause_btn.config(text="Resume Countdown")
            self.countdown_label.config(text="Countdown paused", fg="orange")

    def toggle_countdown(self):
        self.countdown_active = not self.countdown_active
        if self.countdown_active:
            self.pause_btn.config(text="Pause Countdown")
            self.update_countdown()
        else:
            self.pause_btn.config(text="Resume Countdown")
            self.countdown_label.config(text="Countdown paused", fg="orange")

    def update_countdown(self):
        if not self.countdown_active:
            return
        if self.countdown > 0:
            self.countdown_label.config(text=f"Starting monitor in {self.countdown}s…", fg="#0066cc")
            self.countdown -= 1
            self.root.after(1000, self.update_countdown)
        else:
            self.start_monitor()

    # ── Launch the monitor ───────────────────────────────
    def save_and_get_config(self):
        if self.detected_camera and self.detected_camera[0] is not None:
            self.config["CAMERA_INDEX"] = str(self.detected_camera[0])

        self.config["PROCESS_EVERY_N"] = str(int(self.frame_skip_var.get()))
        self.config["MIN_CONF"] = f"{self.conf_var.get():.2f}"
        self.config["CONFIRM_FRAMES"] = str(int(self.confirm_var.get()))
        self.config["TFLITE_THREADS"] = "2"
        self.config["FULLSCREEN"] = "1" if self.fullscreen else "0"
        self.config["DEMO_MODE"] = "1" if self.demo_mode else "0"

        if self.data_enabled_var.get():
            try:
                interval = int(self.data_interval_var.get())
                self.config["DATA_SAVE_INT"] = str(max(1, interval))
            except ValueError:
                self.config["DATA_SAVE_INT"] = "10"
        else:
            self.config["DATA_SAVE_INT"] = "0"

        save_config(self.config)
        return self.config

    def start_monitor(self):
        if not self.detected_camera or self.detected_camera[0] is None:
            self.countdown_label.config(text="Cannot start without a camera", fg="red")
            self.countdown_active = False
            self._handoff_armed = False
            self.root.after(CAMERA_POLL_MS, self.poll_camera_once)
            return

        self.countdown_active = False
        try:
            config = self.save_and_get_config()
        except Exception as e:
            self.countdown_label.config(text=f"Failed to save config: {e}", fg="red")
            self._handoff_armed = False
            self.root.after(CAMERA_POLL_MS, self.poll_camera_once)
            return

        self.countdown_label.config(text="Starting monitor…", fg="green")
        self.root.update()

        env = os.environ.copy()
        for key, value in config.items():
            env[key] = value

        self.root.destroy()

        # Launch pi_deploy.py as a subprocess and wait for it to finish
        try:
            proc = subprocess.Popen(
                [sys.executable, MAIN_SCRIPT],
                env=env,
                cwd=os.path.dirname(os.path.abspath(__file__)),
            )
            sys.exit(proc.wait())
        except Exception as e:
            print(f"[LAUNCHER] Failed to start monitor: {e}", file=sys.stderr)
            sys.exit(1)

    def quit_app(self):
        self.countdown_active = False
        self.root.destroy()
        sys.exit(0)


def main():
    # Default DISPLAY for headless SSH sessions on the Pi
    if not os.environ.get("DISPLAY"):
        os.environ["DISPLAY"] = ":0"

    try:
        root = tk.Tk()
    except tk.TclError as e:
        print(
            "Cannot open an X display (Tkinter).\n"
            "  • On the Pi desktop, open a terminal and run:\n"
            "      cd ~/pit_safety && ./start.sh\n"
            "  • From SSH with a desktop session running:\n"
            "      DISPLAY=:0 ./start.sh\n"
            f"  Details: {e}",
            file=sys.stderr,
        )
        sys.exit(1)

    style = ttk.Style()
    try:
        style.theme_use("clam")
    except Exception:
        pass

    LauncherApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
